# Use root/example as user/password credentials
version: '3.1'

services:
  web:
    image: nginx
    ports:
      - "8080:80"

  socket:
      image: socket
      build: ./socket-io
      command: npm start
      ports: 
        - "5000:5000"
      depends_on: 
        - "mongo"

  backend:
    image: web-auth
    build: ./nodejs_Auth
    command: npm start
    ports: 
      - "3000:3000"
    depends_on: 
      - "mongo"

  mongo:
    image: mongo
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081